#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o

obj-$(CONFIG_SENSORS_MAX86900)	+= max86900.o
obj-$(CONFIG_SENSORS_TMD3782S)	+= taos_tmd3782.o
obj-$(CONFIG_SENSORS_TMD3782)	+= tmd3782.o
obj-$(CONFIG_SENSORS_TMD27723)	+= tmd27723.o
obj-$(CONFIG_SENSORS_AK09911C)	+= ak09911c.o
obj-$(CONFIG_SENSORS_GP2A30)	+= gp2ap030.o
obj-$(CONFIG_SENSORS_BMI055)	+= bma255.o bmg160.o
obj-$(CONFIG_SENSORS_CM3323)	+= cm3323.o
obj-$(CONFIG_SENSORS_SX9500)	+= sx9500.o
obj-$(CONFIG_SENSORS_SX9310_INPUT)      +=sx9310.o
obj-$(CONFIG_SENSORS_BMA2X2)	+= bma2x2.o
obj-$(CONFIG_SENSORS_BMM050)	+= bmm050_driver.o bmm050.o
