
# host notify driver
obj-$(CONFIG_USB_HOST_NOTIFY)		+= host_notify_class.o
obj-$(CONFIG_USB_EXTERNAL_NOTIFY)	+= external_notify.o
obj-$(CONFIG_USB_NOTIFY_LAYER)		+= usb_notify.o usb_notify_sysfs.o
obj-$(CONFIG_USB_NOTIFIER)		+= usb_notifier.o

