#
# Makefile for IIO Light sensors
#

obj-$(CONFIG_SENSORS_SX9306)   +=sx9306_iio.o
obj-$(CONFIG_SENSORS_SX9306_WIFI)   +=sx9306_wifi_iio.o
obj-$(CONFIG_SENSORS_SX9310)   +=sx9310_iio.o
obj-$(CONFIG_SENSORS_SX9310_WIFI)   +=sx9310_wifi_iio.o
